name: Build Paper 
on: 
  push:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile ACM Paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          working_directory: "acmpaper"
      - name: Compile Type2023 Paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: types2023.tex
          working_directory: "types2023"
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: |
            acmpaper/paper.pdf
            types2023/types2023.pdf
